### ISSUE TITLE
Error in PhpStorm

### ISSUE THREAD

**Issue by dehrk** [datreks/codetime-jetbrains#3]
I keep getting this error in PhpStorm

### PhpStorm Version
PhpStorm 2020.3.3
Build #PS-203.7717.64, built on March 16, 2021

### Error
```
com.intellij.serviceContainer.AlreadyDisposedException: Already disposed: Project(name=garage, containerState=DISPOSE_COMPLETED, componentStore=C:\Users\dkinne000\PhpstormProjects\garage) (disposed)
	at com.intellij.serviceContainer.ComponentManagerImpl.checkStateAndGetPicoContainer(ComponentManagerImpl.kt:167)
	at com.intellij.serviceContainer.ComponentManagerImpl.getComponent(ComponentManagerImpl.kt:409)
	at com.intellij.openapi.module.ModuleManager.getInstance(ModuleManager.java:33)
	at com.intellij.openapi.project.ProjectUtil.guessProjectDir(ProjectUtil.kt:131)
	at com.github.si9ma.codetimejetbrains.listeners.CodeTimeProjectManagerListener.submitEventLog(CodeTimeProjectManagerListener.kt:74)
	at com.github.si9ma.codetimejetbrains.listeners.CodeTimeProjectManagerListener.access$submitEventLog(CodeTimeProjectManagerListener.kt:30)
	at com.github.si9ma.codetimejetbrains.listeners.CodeTimeProjectManagerListener$projectOpened$$inlined$timerTask$1.run(Timer.kt:158)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
	at java.base/java.util.TimerThread.run(Timer.java:506)
```

**Comment by si9ma** [comment]
@dehrk Thanks for your feedback. Except for this error, is the plugin working properly?

**Comment by dehrk** [comment]
> 
> 
> @dehrk Thanks for your feedback. Except for this error, is the plugin working properly?

Yup! Seems to be at least.

**Comment by si9ma** [comment]
@dehrk I think this is a warning, I will check it soon.
